name: Thealph
favicon: null
layout_spectrum: 0.2651
typography_spectrum: 0.20945756789296865
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.5
  lightness: 0.6810787543654442
  saturation: 0.47736814548261464
  rhythmicContrast: 0.9153028049040586
purpose: []
